[package]
name = "audown"
version = "0.0.1"
edition = "2021"

[profile.release]
lto = true
strip = true
codegen-units = 1

[dependencies]
ureq = "2.9.1"
urlencoding = "2.1.3"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
serde_yaml = "0.9.29"
url = "2.5.0"
anyhow = "1.0.76"
memchr = "2.6.4"
dialoguer = "0.11.0"
directories = "5.0.1"
soup = "0.5.1"
mini-v8 = "0.4.1"
nom = "7.1.3"
bitflags = "2.4.2"
