[package]
name = "audown"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
nightly = ["tl/simd"]

[dependencies]
tl = "0.7.7"
htmlentity = "1.3.1"
ureq = "2.6.2"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
url = "2.3.1"
anyhow = "1.0.70"
base64 = "0.21.0"
md5 = "0.7.0"
memchr = "2.5.0"
