[package]
name = "audown"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ureq = "2.9.1"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
serde_yaml = "0.9.29"
url = "2.5.0"
anyhow = "1.0.76"
memchr = "2.6.4"
dialoguer = "0.11.0"
new_string_template = "1.4.0"
directories = "5.0.1"
soup = "0.5.1"
mini-v8 = "0.4.1"
